// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZKwOdbkcuyPXKCZYq4507bu0boHeK6aI',
    appId: '1:221329240377:web:d93d62e75770885600b8e8',
    messagingSenderId: '221329240377',
    projectId: 'flutter-firebase-2ebb1',
    authDomain: 'flutter-firebase-2ebb1.firebaseapp.com',
    storageBucket: 'flutter-firebase-2ebb1.appspot.com',
    measurementId: 'G-PTBLCEZMXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpXHPs4OS-FoEedjqiWJyfNMFtNHASok8',
    appId: '1:221329240377:android:598a255a4e12285f00b8e8',
    messagingSenderId: '221329240377',
    projectId: 'flutter-firebase-2ebb1',
    storageBucket: 'flutter-firebase-2ebb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtIaNyee59yaHppzFLsQsIEFbasSrV0As',
    appId: '1:221329240377:ios:55e884e26fb09c0d00b8e8',
    messagingSenderId: '221329240377',
    projectId: 'flutter-firebase-2ebb1',
    storageBucket: 'flutter-firebase-2ebb1.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtIaNyee59yaHppzFLsQsIEFbasSrV0As',
    appId: '1:221329240377:ios:4ff1e51112698a6000b8e8',
    messagingSenderId: '221329240377',
    projectId: 'flutter-firebase-2ebb1',
    storageBucket: 'flutter-firebase-2ebb1.appspot.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
